#!/bin/sh
# postinst script for dkms
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        kconf="/etc/kernel-img.conf"
        hookline="header_postinst_hook = /etc/kernel/postinst.d/dkms"
        
        if [ -e $kconf ]; then
            if ! grep -q "$hookline" "$kconf" ; then
                echo "$hookline" >> $kconf
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
