#!/bin/sh

set -e

kconf="/etc/kernel-img.conf"
hookline="header_postinst_hook = /etc/kernel/postinst.d/dkms"

if [ -e $kconf ]; then
    if grep -q "$hookline" "$kconf" ; then
        sed -i "\@$hookline@d" "$kconf"
    fi
fi

#DEBHELPER#

exit 0
